
		<div id="slider">
			<ul class="thumbnails">
			  <li class="span4">
				<div class="thumbnail">
				  <img src="<?php echo $this->basePath('img/room.jpg');?>" alt="Rooms">
				  <h3 align="Center"><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'nastanqvane')); ?>">Стаи</a></h3>
				  <p>Всички стаи и апартаменти  са с великолепни гледки към града, планинските склонове или градината на хотела. Стаите са елегантно и модерно обзаведени и предлагат уют, комфорт и простор.</p>				</div>
			  </li>
			  <li class="span4">
				<div class="thumbnail">
				  <img src="<?php echo $this->basePath('img/spa.jpg');?>" alt="Spa">
				  <h3 align="Center"><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'spa')); ?>">СПА</a></h3>
				  <p> За да бъде отдихът Ви наистина лечебен, може да се възползвате от физиотерапевтичните процедури ,кало и луголечение,както и от водноструевия масаж на тангенторната вана.</p>
				</div>
			  </li>
			   <li class="span4">
				<div class="thumbnail">
				  <img src="<?php echo $this->basePath('img/garden.jpg');?>" alt="Garden">
				  <h3 align="Center"><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'garden')); ?>">Градина</a></h3>
				  <p>
За Вашата почивка или бизнес мероприятие Ви предлагаме уютна атмосфера и стил, изключително спокойствие, комфорт и възможност да се насладите на прекрасната ни градина.</p>
				</div>
			  </li>
			</ul>
	</div>
