
		<div id="slider">
			<ul class="thumbnails">
			  <li class="span4">
				<div class="thumbnail">
				  <img src="<?php echo $this->basePath('img/nachalo1.jpg');?>" alt="About Us">
				  <h3 align="Center"><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'aboutus')); ?>">За нас</a></h3>
				  <p>Spa Hotel Persenk се гордее с луксозен и стилен интериор, висококачествени услуги, както и с елегантно обзаведени, удобни и просторни стаи с възхитителни гледки към Девин и Родопите.</p>
				</div>
			  </li>
			  <li class="span4">
				<div class="thumbnail">
				  <img src="<?php echo $this->basePath('img/nastanqvane1.jpg');?>" alt="Check in">
				  <h3 align="Center"><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'nastanqvane')); ?>">Настаняване</a></h3>
				  <p>Всички стаи и апартаменти  са с великолепни гледки към града, планинските склонове или градината на хотела. Стаите са елегантно и модерно обзаведени и предлагат уют, комфорт и простор.
</p>
				</div>
			  </li>
			   <li class="span4">
				<div class="thumbnail">
				  <img src="<?php echo $this->basePath('img/galeriq1.jpg');?>" alt="Gallery">
				  <h3 align="Center"><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'gallery')); ?>">Галерия</a></h3>
				  <p>В нашата галерия може да видите интериора, елегантното обзавеждане и просторните стаи на хотела, СПА салона с различните процедури и възхитителните гледки към Девин и Родопите. </p>
				</div>
			  </li>
			</ul>
	</div>
