
		<div id="slider">
			<ul class="thumbnails">
			  <li class="span4">
				<div class="thumbnail">
				  <img src="<?php echo $this->basePath('img/edin.jpg');?>" alt="One">
				  <h3 align="Center"><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'edin')); ?>">Единична стая</a></h3>
				  <p>Всички стаи и апартаменти  са с великолепни гледки към града, планинските склонове или градината на хотела. Стаите са елегантно и модерно обзаведени и предлагат уют, комфорт и простор.
</p>
				</div>
			  </li>
			  <li class="span4">
				<div class="thumbnail">
				  <img src="<?php echo $this->basePath('img/dva.jpg');?>" alt="Two">
				  <h3 align="Center"><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'dvoina')); ?>">Двойна стая</a></h3>
				  <p>Всички стаи и апартаменти  са с великолепни гледки към града, планинските склонове или градината на хотела. Стаите са елегантно и модерно обзаведени и предлагат уют, комфорт и простор.</p>
				</div>
			  </li>
			   <li class="span4">
				<div class="thumbnail">
				  <img src="<?php echo $this->basePath('img/apart.jpg');?>" alt="Apart">
				  <h3 align="Center"><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'apart')); ?>">Апартамент</a></h3>
				  <p>Всички стаи и апартаменти  са с великолепни гледки към града, планинските склонове или градината на хотела. Стаите са елегантно и модерно обзаведени и предлагат уют, комфорт и простор.</p>
				</div>
			  </li>
			</ul>
	</div>
