<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta content=" English">
	<meta name="description" content ="Spa Hotel Persenk">
	<meta name="keywords" content="spa,hotel,persenk,holiday">
	<meta name="Author" content="www.spahotelpersenk.com">
	<meta name="Copyright " content="Copyright (c)  SpaHotelPersenk">
	<meta name="town" content="Pazardjik">
	<meta name="distribution" content="Global">
	<title>Спа Хотел "Персенк"</title>
	<link href="<?php echo $this->basePath('css/styles.css');?>" rel="stylesheet" type="text/css" href="css/styles.css">
	<link href="<?php echo $this->basePath('css/style_nav.css');?>" rel="stylesheet" type="text/css" href="css/style_nav.css">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
	<link href="<?php echo $this->basePath('css/bootstrap.min.css');?>" rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
	<!-- Responsive Design-->
	
	
	</head>
	
	<body>
		<div class="main">
		<div class="container">
	
		<header>
				<div id="searchBox">
			<div id="searchBoxBorder"></div>
				<div align="center"><h5>Вашето място е при нас...</h5></b></div>
			</div>
				
				<div id="logo">
					<IMG src="<?php echo $this->basePath('img/logonovo.png');?>" width="200" height="150" alt="Logo">
				</div>	
					
				<div id="loginMenu">
					<div id="slider">
					<div id="searchBoxBorder"></div>

						<ul class="inline" align="center">
							<?php if(!$user = $this->identity()){?>
							<li><a href='<?php echo $this->url('login'); ?>'><h5>Вход</h5></a></li>
							<li><a href='<?php echo $this->url('registration'); ?>'><h5>Регистрация</h5></a></li>
							<?php }else
							{ ?>
							<li><a href='<?php echo $this->url('user'); ?>'><h5>Потребител</h5></a></li>
							<li><a href='<?php echo $this->url('editProfile'); ?>'><h5>Промени профил</h5></a></li>
							<li><a href='<?php echo $this->url('logout'); ?>'><h5>Изход</h5></a></li>
							<?php
							} ?>
						</ul>
						
					</div>
				</div>

				<div style="clear: both"></div>

				<nav>
					<div class="navbar navbar-inverse">
						 <div class="navbar-inner">
							<div class="container" >
						 
							  <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
							  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							  </a>
						 
							  <!-- Be sure to leave the brand out there if you want it shown -->
							  <ul class="nav" >
							  <?php if(!$user = $this->identity()){?>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'index')); ?>">НАЧАЛО</a></li>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'aboutus')); ?>">ЗА НАС</a></li>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'gallery')); ?>">ГАЛЕРИЯ</a></li>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'nastanqvane')); ?>">НАСТАНЯВАНЕ</a></li>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'contact')); ?>">КОНТАКТИ</a></li> 
							<?php }else
							{ ?>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'index')); ?>">НАЧАЛО</a></li>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'aboutus')); ?>">ЗА НАС</a></li>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'gallery')); ?>">ГАЛЕРИЯ</a></li>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'nastanqvane')); ?>">НАСТАНЯВАНЕ</a></li>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'prices')); ?>">ЦЕНИ</a></li>
								  <li><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'contact')); ?>">КОНТАКТИ</a></li> 
							<?php
							} ?>
								 
							 </ul>
	
							<form class="navbar-search pull-right">
									<input type="text" class="search-query" placeholder="Търсене">
							</form>
							
							<!-- Everything you want hidden at 940px or less, place within here -->
							  
							<!-- .nav, .navbar-search, .navbar-form, etc -->
							  <
							</div>
						  </div>
						</div>
				</nav>
				
			</header>

			<div id="myCarousel" class="carousel slide">
			  <ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
			  </ol>
			  <!-- Carousel items -->
			  <div class="carousel-inner">
				<div class="active item"><img src="<?php echo $this->basePath('img/r3.jpg');?>" width="1000" alt="Slider"></div>
				<div class="item"><img src="<?php echo $this->basePath('img/r2.jpg');?>" width="1000" alt="Slider"></div>
				<div class="item"><img src="<?php echo $this->basePath('img/r1.jpg');?>" width="1000" alt="Slider"></div>
			  </div>
			  <!-- Carousel nav -->
			  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
			  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
			</div>
			
			<div id="content">
				<?php echo $this->content; ?>
			</div>
		
		
			<footer>
				<div id="borderSolid">
					<ul class="thumbnails">
					  <li class="span4">
					  <div  align="center">
						<h4> Начини на плащане</h4>
						<p>PayPal плащане<p><img src="<?php echo $this->basePath('img/cards.jpg');?>" width="140" alt="Methods of payment"></p></p>
						<p>С банков трансфер</p>
					  </div>
					  </li>
					  
					  <li class="span4"> 
					  <div align="center">
					  <h4> За нас</h4>
					  <p> <a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'aboutus')); ?>">
					  <img src="<?php echo $this->basePath('img/logonovo2.png');?>" width="200" height="100" alt="About us">
					  </a>
					  </p>
					  </div>
					  </li>
					  
					  
					  <li class="span4">
					  <div align="center">
					  <div id="slider">
					  <h4>Помощ за нашите клиенти</h4> 
					  	<p><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'mest')); ?>">Местоположение</a></p>
						<p><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'nastanqvane')); ?>">Настаняване</a></p>
						<p><a href="<?php echo $this->url('btk/default',array('controller'=>'index','action'=>'contact')); ?>">Контакти</a></p>	  
					  </div>
					  </div>
					  </li>
					</ul>
				</div>		
			</footer>
		</div>
		</div>

		<script src="http://code.jquery.com/jquery.js"></script>
		<script src="<?php echo $this->basePath('js/bootstrap.min.js');?>" ></script>

	</body>
</html>
